export const popular = [
{
"adult":false,
"backdrop_path":"/srYya1ZlI97Au4jUYAktDe3avyA.jpg",
"genre_ids":[14,28,12],
"id":464052,
"original_language":"en",
"original_title":"Wonder Woman 1984",
"overview":"Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.",
"popularity":3906.05,
"poster_path":"/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg",
"release_date":"2020-12-16",
"title":"Wonder Woman 1984",
"video":false,
"vote_average":7.2,
"vote_count":2553
},
{
"adult":false,
"backdrop_path":"/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg",
"genre_ids":[16,35,18,10402,14],
"id":508442,
"original_language":"en",
"original_title":"Soul",
"overview":"Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club,he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar,a center in which souls develop and gain passions before bein transported to a newborn child. Joe must enlist help from the other souls-in-training,like 22,a soul who has spent eons in the You Seminar,in order to get back to Earth.",
"popularity":3646.51,
"poster_path":"/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg",
"release_date":"2020-12-25",
"title":"Soul",
"video":false,
"vote_average":8.4,
"vote_count":3358
},

{
"adult":false,
"backdrop_path":"/ibwOX4xUndc6E90MYfglghWvO5Z.jpg",
"genre_ids":[878,12],
"id":517096,
"original_language":"ru",
"original_title":"Вратарь Галактики",
"overview":"Cosmoball is a mesmerizing intergalactic game of future played between humans and aliens at the giant extraterrestrial ship hovering in the sky over Earth. A young man with enormous power of an unknown nature joins the team of hot-headed superheroes in exchange for a cure for his mother’s deadly illness. The Four from Earth will fight not only to defend the honor of their home planet in the spectacular game,but to face the unprecedented threat to the Galaxy and embrace their own destiny.",
"popularity":2285.792,
"poster_path":"/eDJYDXRoWoUzxjd52gtz5ODTSU1.jpg",
"release_date":"2020-08-27",
"title":"Cosmoball",
"video":false,
"vote_average":4.9,
"vote_count":44
},

{

"adult":false,
"backdrop_path":"/yR27bZPIkNhpGEIP3jKV2EifTgo.jpg",
"genre_ids":[16,10751],
"id":755812,
"original_language":"fr",
"original_title":"Miraculous World: New York, United HeroeZ",
"overview":"During a school field trip,Ladybug and Cat Noir meet the American superheroes,whom they have to save from an akumatised super-villain. They discover that Miraculous exist in the United States too.",
"popularity":1687.584,
"poster_path":"/kIHgjAkuzvKBnmdstpBOo4AfZah.jpg",
"release_date":"2020-10-10",
"title":"Miraculous World: New York,United HeroeZ",
"video":false,
"vote_average":8.6,
"vote_count":272
},
{
"adult":false,
"backdrop_path":"/9pHxv7TX0jOKNgnGMDP6RJ2m1GL.jpg",
"genre_ids":[28,53],
"id":737568,
"original_language":"en",
"original_title":"The Doorman",
"overview":"A former Marine turned doorman at a luxury New York City high-rise must outsmart and battle a group of art thieves and their ruthless leader — while struggling to protect her sister's family. As the thieves become increasingly desperate and violent,the doorman calls upon her deadly fighting skills to end the showdown.",
"popularity":1613.287,
"poster_path":"/pklyUbh4k1DbHdnsOMASyw7C6NH.jpg",
"release_date":"2020-10-01",
"title":"The Doorman",
"video":false,
"vote_average":6.1,
"vote_count":109
},
{
"adult":false,
"backdrop_path":"/dueiWzWc81UAgnbDAyH4Gjqnh4n.jpg",
"genre_ids":[18,878],
"id":614911,
"original_language":"en",
"original_title":"The Midnight Sky",
"overview":"A lone scientist in the Arctic races to contact a crew of astronauts returning home to a mysterious global catastrophe.",
"popularity":1478.849,
"poster_path":"/51JxCk77ZCqLzbLkrDl9Qho6KUh.jpg",
"release_date":"2020-12-10",
"title":"The Midnight Sky",
"video":false,
"vote_average":5.9,
"vote_count":872
},
{
"adult":false,
"backdrop_path":"/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg",
"genre_ids":[28,12,80],
"id":604822,
"original_language":"zh",
"original_title":"急先锋",
"overview":"Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
"popularity":1797.379,
"poster_path":"/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg",
"release_date":"2020-09-30",
"title":"Vanguard",
"video":false,
"vote_average":7.4,
"vote_count":126
},
{
"adult":false,
"backdrop_path":"/z15NpieRw7jL7bKoICwLO5j7FgZ.jpg",
"genre_ids":[878],
"id":733317,
"original_language":"en",
"original_title":"Monsters of Man",
"overview":"A robotics company vying to win a lucrative military contract team up with a corrupt CIA agent to conduct an illegal live field test. They deploy four weaponized prototype robots into a suspected drug manufacturing camp in the Golden Triangle,assuming they'd be killing drug runners that no one would miss. Six doctors on a humanitarian mission witness the brutal slaughter and become prime targets.",
"popularity":1284.215,
"poster_path":"/1f3qspv64L5FXrRy0MF8X92ieuw.jpg",
"release_date":"2020-11-19",
"title":"Monsters of Man",
"video":false,
"vote_average":7.2,
"vote_count":116
},
{
"adult":false,
"backdrop_path":"/cjaOSjsjV6cl3uXdJqimktT880L.jpg",
"genre_ids":[12,14,10751,16],
"id":529203,
"original_language":"en",
"original_title":"The Croods: A New Age",
"overview":"Searching for a safer habitat,the prehistoric Crood family discovers an idyllic  walled-in paradise that meets all of its needs. Unfortunately,they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors star to rise,a new threat soon propels both clans on an epic adventure that forces them to embrace their differences,draw strength from one another,and survive together.",
"popularity":1419.345,
"poster_path":"/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg",
"release_date":"2020-11-25",
"title":"The Croods: A New Age",
"video":false,
"vote_average":7.8,
"vote_count":1084
},
{
"adult":false,
"backdrop_path":"/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg",
"genre_ids":[28,53,80,18],
"id":553604,
"original_language":"en",
"original_title":"Honest Thief",
"overview":"A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him,he must fight back to clear his name.",
"popularity":1207.128,
"poster_path":"/zeD4PabP6099gpE0STWJrJrCBCs.jpg",
"release_date":"2020-09-03",
"title":"Honest Thief",
"video":false,
"vote_average":6.7,
"vote_count":440
},
{
"adult":false,
"backdrop_path":"/wk58aoyWpMTVkKkdjw889XfWGdL.jpg",
"genre_ids":[53,80,9648],
"id":646593,
"original_language":"en",
"original_title":"Wander",
"overview":"After getting hired to probe a suspicious death in the small town of Wander,a mentally unstable private investigator becomes convinced the case is linked to the same 'conspiracy cover up' that caused the death of his daughter.",
"popularity":979.467,
"poster_path":"/2AwPvNHphpZBJDqjZKVuMAbvS0v.jpg",
"release_date":"2020-12-04",
"title":"Wander",
"video":false,
"vote_average":5.2,
"vote_count":77
},
{
"adult":false,
"backdrop_path":"/wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
"genre_ids":[28,53,878],
"id":577922,
"original_language":"en",
"original_title":"Tenet",
"overview":"Armed with only one word - Tenet - and fighting for the survival of the entire world,the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
"popularity":1090.18,
"poster_path":"/k68nPLbIST6NP96JmTxmZijEvCA.jpg",
"release_date":"2020-08-22",
"title":"Tenet",
"video":false,
"vote_average":7.3,
"vote_count":3854
},
{
"adult":false,
"backdrop_path":"/UgNke0mMQhQdnX2hEu4cN83M0a.jpg",
"genre_ids":[28,14,10751],
"id":615677,
"original_language":"en",
"original_title":"We Can Be Heroes",
"overview":"When alien invaders capture Earth's superheroes,their kids must learn to work together to save their parents - and the planet.",
"popularity":1075.185,
"poster_path":"/1S21HpcKY6uQ9UAw68aICmrJaq6.jpg",
"release_date":"2020-12-25",
"title":"We Can Be Heroes",
"video":false,
"vote_average":6.1,
"vote_count":218
},
{
"adult":false,
"backdrop_path":"/2Fk3AB8E9dYIBc2ywJkxk8BTyhc.jpg",
"genre_ids":[28,53],
"id":524047,
"original_language":"en",
"original_title":"Greenland",
"overview":"John Garrity,his estranged wife and their young son embark on a perilous journey to find sanctuary as a planet-killing comet hurtles toward Earth. Amid terrifying accounts of cities getting levelled, the Garrity's experience the best and worst in humanity. As the countdown to the global apocalypse approaches zero,their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.",
"popularity":1028.706,
"poster_path":"/bNo2mcvSwIvnx8K6y1euAc1TLVq.jpg",
"release_date":"2020-07-29",
"title":"Greenland",
"video":false,
"vote_average":7.1,
"vote_count":1319
},
{
"adult":false,
"backdrop_path":"/lWf1aiqDZqUbhrw8DnsfV8Ql7CP.jpg",
"genre_ids":[10751,16,35,12],
"id":777350,
"original_language":"en",
"original_title":"Dory's Reef Cam",
"overview":"Dive into the waters below and watch the aquatic wildlife from the world of Nemo and Dory.",
"popularity":846.691,
"poster_path":"/mMWLGu9pFymqipN8yvISHsAaj72.jpg",
"release_date":"2020-12-18",
"title":"Dory's Reef Cam",
"video":false,
"vote_average":6.6,
"vote_count":10
},
{
"adult":false,
"backdrop_path":"/aHYUj0hICtWZ5tPiCIm6pWUcjYK.jpg",
"genre_ids":[28,18,27,10752],
"id":675327,
"original_language":"en",
"original_title":"Shadow in the Cloud",
"overview":"A WWII pilot traveling with top secret documents on a B-17 Flying Fortress encounters an evil presence on board the flight.",
"popularity":1375.004,
"poster_path":"/t7EUMSlfUN3jUSZUJOLURAzJzZs.jpg",
"release_date":"2020-12-31",
"title":"Shadow in the Cloud",
"video":false,
"vote_average":6.2,
"vote_count":126
},
{
"adult":false,
"backdrop_path":"/jeAQdDX9nguP6YOX6QSWKDPkbBo.jpg",
"genre_ids":[28,14,878],
"id":590706,
"original_language":"en",
"original_title":"Jiu Jitsu",
"overview":"Every six years, an ancient order of jiu-jitsu fighters joins forces to battle a vicious race of alien invaders. But when a celebrated war hero goes down in defeat, the fate of the planet and mankind hangs in the balance.",
"popularity":895.361,
"poster_path":"/eLT8Cu357VOwBVTitkmlDEg32Fs.jpg",
"release_date":"2020-11-20",
"title":"Jiu Jitsu",
"video":false,
"vote_average":5.3,
"vote_count":242
},
{
"adult":false,
"backdrop_path":"/lrzAb9QCwKPOwH1iY7WpfjR6jcC.jpg",
"genre_ids":[10770,53],
"id":648371,
"original_language":"en",
"original_title":"No Good Deed",
"overview":"Karen never planned on being a hero. A recent widow,she has her hands full with work and parenting her son Max. Then Karen saves Jeremy's life during a drug store robbery and quickly discovers that the young man is intent on paying her back at any cost. At first,life starts improving for this good Samaritan, but as Jeremy's efforts become more extreme,Karen starts to wonder if no good deed truly goes unpunished.",
"popularity":664.196,
"poster_path":"/27BnREBR5rcMrUVUhV5bTXlcCym.jpg",
"release_date":"2020-03-13",
"title":"No Good Deed",
"video":false,
"vote_average":6.5,
"vote_count":28
},
{
"adult":false,
"backdrop_path":"/ckfwfLkl0CkafTasoRw5FILhZAS.jpg",
"genre_ids":[28,35,14],
"id":602211,
"original_language":"en",
"original_title":"Fatman",
"overview":"A rowdy,unorthodox Santa Claus is fighting to save his declining business. Meanwhile,Billy,a neglected and precocious 12 year old,hires a hit man to kill Santa after receiving a lump of coal in his stocking.",
"popularity":618.167,
"poster_path":"/4n8QNNdk4BOX9Dslfbz5Dy6j1HK.jpg",
"release_date":"2020-11-13",
"title":"Fatman",
"video":false,
"vote_average":5.6,
"vote_count":321
},
{
"adult":false,
"backdrop_path":"/sFLgXQGrSWxnjmPOpGKPApWNOUH.jpg",
"genre_ids":[36,28,12],
"id":635237,
"original_language":"pt",
"original_title":"Arthur & Merlin: Knights of Camelot",
"overview":"King Arthur returns home after fighting the Roman Empire. His illegitimate son has corrupted the throne of Camelot and King Arthur must reunite with the wizard Merlin and the Knights of the Round Table to fight to get back his crown.",
"popularity":621.282,
"poster_path":"/chGTXsvn53XvEnvsJ9ZD9eiYKx9.jpg",
"release_date":"2020-05-28",
"title":"Arthur & Merlin: Knights of Camelot",
"video":false,
"vote_average":5.5,
"vote_count":73
}

];